ipv4 = "10.0.10.1/24"
listeners = [
    "tcp://0.0.0.0:22022",
    "udp://0.0.0.0:22022",
]
rpc_portal = "0.0.0.0:0"
tcp_whitelist = []
udp_whitelist = []

[network_identity]
network_name = "change-me"
network_secret = "change-me-to-a-random-string"

[flags]
private_mode = true
